language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"

# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - export LLVM_VERSION=3.4
  - sudo apt-get install llvm-${LLVM_VERSION} clang-${LLVM_VERSION} libapr1-dev libaprutil1-dev
  - sudo apt-get install dragonegg llvm-${LLVM_VERSION} llvm-gcc-4.7
  - sudo pip install -e .
  - export WLLVM_HOME=`pwd`
  - export APACHE_VER=2.4.18


# command to run tests
script:
  # build apache with clang (i.e. httpd-2.4.12) 
  - ${WLLVM_HOME}/.travis/apache_clang.sh
  # build apache with gcc and dragonegg (i.e. httpd-2.4.12) 
  - ${WLLVM_HOME}/.travis/apache_dragonegg.sh
  

