language: python

sudo: required
dist: trusty

python:
  - "3.3"
  - "2.7"
  - "2.6"


# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - sudo apt-get install  -y llvm-3.5 clang-3.5 libapr1-dev libaprutil1-dev
  # dragonegg uses 3.3
  - sudo apt-get install  -y llvm-3.3 llvm-gcc-4.7
  - sudo pip install -e .
  - export WLLVM_HOME=`pwd`
  - export APACHE_VER=2.4.18


# command to run tests
script:
  # build apache with clang
  - ${WLLVM_HOME}/.travis/apache_clang.sh
  # build apache with gcc and dragonegg
  - ${WLLVM_HOME}/.travis/apache_dragonegg.sh
  

